---
    version: '2'
    services:
        zookeeper:
            image: wurstmeister/zookeeper
            ports:
              - "2181:2181"
        kafka-broker:
            image: apache-kafka/broker:2.5.0
            hostname: kafka-broker
            container_name: kafka-broker
            ports:
                - "9092:9092"            
            environment:
                - KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
                - KAFKA_ADVERTISED_HOST_NAME: 10.131.138.166
                - KAFKA_CREATE_TOPICS: "test:1:1"
            volumes:
                - /var/run/docker.sock:/var/run/docker.sock